//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_Final_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activities
    {
        public int Id { get; set; }
        public System.DateTime Date_Modified { get; set; }
        public string Table_Name { get; set; }
        public string Message { get; set; }
        public string Element_ID { get; set; }
    }
}
